FROM python:3.10-slim

WORKDIR /backend

COPY ./api/requirements.txt /backend/requirements.txt
RUN pip install --no-cache-dir -r /backend/requirements.txt

RUN python -m spacy download en_core_web_trf

COPY ./api /backend

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
