services:
  frontend:
    build:
      context: ./
      dockerfile: DockerFile.frontend
    image: abhishek1231/crammaster-frontend:latest
    volumes:
      - shared-data:/app/shared/uploads
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_ENDPOINT: ${NEXT_PUBLIC_API_ENDPOINT}
      NEXT_PUBLIC_UPLOAD_DIR: ${NEXT_PUBLIC_UPLOAD_DIR}
    depends_on:
      - backend

  backend:
    build:
      context: ./
      dockerfile: DockerFile.backend
    image: abhishek1231/crammaster-backend:latest
    volumes:
      - shared-data:/app/shared/uploads
    ports:
      - "8000:8000"

volumes:
  shared-data:
