FROM python:3.13-alpine

WORKDIR /CramMaster/src/api

COPY CramMaster/src/api/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the app
COPY CramMaster/src/api .

# Expose port and run app
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]